version: '3.8'

services:
  carteira-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carteira-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["pnpm", "start"]
    restart: unless-stopped
